# Generated by Django 3.2 on 2022-11-04 13:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=12, unique=True)),
                ('amount', models.CharField(max_length=15)),
                ('time_earned', models.DateTimeField(default=datetime.datetime.today)),
            ],
            options={
                'ordering': ('-time_earned',),
            },
        ),
        migrations.CreateModel(
            name='ReferralBonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=12, unique=True)),
                ('paid', models.BooleanField(default=False)),
                ('date_pained', models.DateTimeField(default=datetime.datetime.today)),
            ],
            options={
                'ordering': ('-date_pained',),
            },
        ),
        migrations.CreateModel(
            name='Referred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personwhorefferred', models.CharField(max_length=12, unique=True)),
                ('personrefferred', models.CharField(max_length=25, unique=True)),
                ('date_refferred', models.DateTimeField(default=datetime.datetime.today)),
            ],
            options={
                'ordering': ('-date_refferred',),
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=12, unique=True)),
                ('date_withdraw', models.DateTimeField(default=datetime.datetime.today)),
                ('amount', models.CharField(max_length=12)),
                ('phone', models.CharField(default=1, max_length=12)),
                ('txt_random', models.CharField(default=1, max_length=12)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.currencie')),
            ],
            options={
                'ordering': ('-date_withdraw',),
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=12, unique=True)),
                ('date_deposit', models.DateTimeField(default=datetime.datetime.today)),
                ('amount', models.CharField(max_length=12)),
                ('phone', models.CharField(default=1, max_length=12)),
                ('txt_random', models.CharField(default=1, max_length=12)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.currencie')),
            ],
            options={
                'ordering': ('-date_deposit',),
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=12)),
                ('date_deposited', models.DateTimeField(default=datetime.datetime.today)),
                ('person', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_deposited',),
            },
        ),
    ]
