# Generated by Django 3.2 on 2022-11-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221104_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='currency',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='phone',
            new_name='transID',
        ),
        migrations.AddField(
            model_name='deposit',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deposit',
            name='wallet',
            field=models.CharField(default=1, max_length=12),
        ),
    ]
