# Generated by Django 3.2 on 2022-11-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221105_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='currency',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='phone',
            new_name='transID',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wallet',
            field=models.CharField(default=1, max_length=12),
        ),
    ]
