# Generated by Django 3.2 on 2022-11-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20221108_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='person',
            field=models.CharField(max_length=12),
        ),
    ]
