# Generated by Django 3.2 on 2022-11-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_deposit_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='method',
            new_name='currency',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='transID',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='wallet',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='phone',
            field=models.CharField(default=1, max_length=12),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='person',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
