# Generated by Django 3.2 on 2022-11-16 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20221115_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referred',
            name='personrefferred',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='referred',
            name='personwhorefferred',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
