# Generated by Django 3.2 on 2022-11-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20221116_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referred',
            name='personrefferred',
            field=models.CharField(max_length=12),
        ),
    ]
