# Generated by Django 3.2 on 2022-11-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='person',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='earning',
            name='person',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='referralbonu',
            name='person',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='person',
            field=models.CharField(max_length=12),
        ),
    ]
