# Generated by Django 3.2 on 2022-11-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20221118_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='referred',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
