# Generated by Django 3.2 on 2022-11-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_referred_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referred',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
