# Generated by Django 3.2 on 2022-11-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_referred_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralbonu',
            name='amount',
            field=models.CharField(default=12, max_length=1000),
        ),
        migrations.AlterField(
            model_name='referralbonu',
            name='person',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
