# Generated by Django 3.2 on 2022-11-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20221119_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='person',
            field=models.CharField(max_length=1000),
        ),
    ]
