# Generated by Django 3.2 on 2022-11-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_balance_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='currency',
            new_name='method',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
