# Generated by Django 3.2 on 2022-11-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20221119_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referred',
            name='personwhorefferred',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
