# Generated by Django 3.2 on 2022-11-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_referred_personwhorefferred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='method',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='transID',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='method',
        ),
        migrations.DeleteModel(
            name='Currencie',
        ),
    ]
