# Generated by Django 3.2 on 2022-11-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20221121_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='phone',
            new_name='address',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.wallet'),
        ),
    ]
