# Generated by Django 3.2 on 2022-11-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20221122_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
