# Generated by Django 3.2 on 2022-11-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_balance_date_deposited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='top',
        ),
    ]
